CREATE TABLE IF NOT EXISTS users(
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(20) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
  id SERIAL PRIMARY KEY,
  description VARCHAR(50) NOT NULL,
  deadline VARCHAR(20) NOT NULL,
  status BOOLEAN DEFAULT FALSE,
  user_id INT REFERENCES users(id)
);

SELECT * FROM users;
SELECT * FROM tasks;